name: "Deployment"
description: "Automatically deploy your applications to your deployment server"
author: "Duxcore"
inputs:
  config:
    description: "The configuration path"
    default: ".deployment.json"
    required: false
  deployment-url:
    description: "The URL that the payload is deployed to."
    required: true
  service-id:
    description: "The id of the service you want to deploy."
    required: true
  service-secret:
    description: "The secret of the service you want to deploy."
    required: true
  api-bearer:
    description: "The bearer id of the api credentials."
    required: true
  api-secret:
    description: "The api secret that authorizes the api bearer."
    required: true
  branch:
    description: "The branch that contains the most up to date configuration"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
