name: "Deployment"
description: "Automatically deploy your applications to your deployment server"
author: "Duxcore"
inputs:
  config:
    description: "The configuration path"
    default: ".deployment.json"
    required: false
  deployment-url:
    description: "The URL that the payload is deployed to."
    required: true
  deployment-secret:
    description: "The the secret used to authenticate the deployment."
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
